package meta

import "time"

// SubjectKind distinguishes the three kinds of actor (ADR 0004). Anonymous is
// one of them, not an absence of one: there is a single authorization path and
// no bypass branch.
type SubjectKind string

// The subject kinds.
const (
	User      SubjectKind = "user"
	Robot     SubjectKind = "robot"
	Anonymous SubjectKind = "anonymous"
)

// Valid reports whether k is a known subject kind.
func (k SubjectKind) Valid() bool {
	switch k {
	case User, Robot, Anonymous:
		return true
	default:
		return false
	}
}

// AnonymousSubjectName is the reserved name of the built-in anonymous subject.
// It is seeded once and cannot be deleted: removing it would turn every
// unauthenticated request into a special case.
const AnonymousSubjectName = "anonymous"

// Subject is a user, a robot account, or the anonymous subject. IDs are
// supplied by the caller rather than generated by the store, which keeps
// identifier policy in one place and tests deterministic.
type Subject struct {
	ID        string
	Kind      SubjectKind
	Name      string
	Disabled  bool
	CreatedAt time.Time
}

// SubjectGroup is a local group of subjects. It exists only as a binding
// target: groups hold no permissions themselves and do not nest (ADR 0001).
//
// It is named SubjectGroup rather than Group because this system already has
// group *repositories*, and confusing the two would be easy and expensive.
type SubjectGroup struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

// Role is a named set of permission verbs. Built-in roles ship read-only:
// the store refuses to modify or delete them, so an operator cannot quietly
// redefine what "admin" means.
type Role struct {
	Name    string
	Builtin bool
	// Verbs are stored expanded and explicit -- never wildcards (ADR 0002),
	// so the vocabulary enumeration test and the explainer both see concrete
	// verbs.
	Verbs []string
}

// PrincipalKind says whether a binding attaches to a subject or a group.
type PrincipalKind string

// The principal kinds.
const (
	PrincipalSubject PrincipalKind = "subject"
	PrincipalGroup   PrincipalKind = "group"
)

// Valid reports whether k is a known principal kind.
func (k PrincipalKind) Valid() bool {
	switch k {
	case PrincipalSubject, PrincipalGroup:
		return true
	default:
		return false
	}
}

// Binding grants a role to a principal within a scope. Bindings are the only
// thing that confers permission, and they are purely additive: there are no
// deny rules (ADR 0001).
type Binding struct {
	ID string
	// PrincipalKind and PrincipalID identify the subject or group.
	PrincipalKind PrincipalKind
	PrincipalID   string
	// Role is the role name.
	Role string
	// Scope is a validated scope string: "system", "*", an exact repository
	// name, or a trailing-wildcard pattern. The store keeps it opaque; the
	// grammar belongs to authz.
	Scope     string
	CreatedAt time.Time
}

// EffectiveBinding is a binding that applies to a subject, together with how
// it reached them. ViaGroup is what lets the explainer answer "why does alice
// have this?" with "through the platform-team group" rather than just "she
// does" (ADR 0001, Z-013).
type EffectiveBinding struct {
	Binding
	// ViaGroup names the group that carried the binding, or is empty when the
	// binding is attached to the subject directly.
	ViaGroup string
}

// SubjectPage is one page of subjects.
type SubjectPage struct {
	Subjects   []Subject
	NextCursor string
}
